In [1]:
import numpy as np

**Length of Vector**

In [4]:
def compute_vector_length(vector):
    len_of_vector = np.sum(vector**2)
    return len_of_vector

In [5]:
data = np.array([1, 2, 3]).T
print(compute_vector_length(data))

14


**Dot product**

In [2]:
def compute_dot_product(vector1 , vector2):
    result = np.dot(vector1, vector2)
    return result

In [7]:
v1 = np.array([2, 3, 2]).T
v2 = np.array([-1, 2, 3]).T
print(compute_dot_product(v1, v2))

10


**Multiplication: a vector by a matrix**

In [8]:
def matrix_multi_vector(matrix, vector):
    result = matrix @ vector
    return result

In [9]:
v3 = np.array([1, 2, 3]).T
m1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(matrix_multi_vector(m1, v3))

[14 32 50]


**Multiplication: a matrix by a matrix**

In [10]:
def matrix_multi_matrix(matrix1, matrix2):
    len_of_vector = np.matmul(matrix1, matrix2)
    return len_of_vector

In [11]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
matrix_multi_matrix(a, b)

array([[4, 1],
       [2, 2]])

**Matrix Inverse**
\begin{equation}
    \text{Given}: A = \begin{bmatrix}
    -2 & 6\\
    8 & -4
    \end{bmatrix}
\end{equation}

\begin{equation}
    det(A) = ad - bc = -2*(-4) - 8*6 = -40
\end{equation}

\begin{equation}
    \text{Inverse Matrix}: A^{-1} = \frac{1}{det(A)}
    \begin{bmatrix}
        -4 & -6\\
        -8 & -2
    \end{bmatrix}
    =
        \begin{bmatrix}
        \frac{1}{10} & \frac{3}{20}\\
        \frac{1}{5} & \frac{1}{20}
    \end{bmatrix}
\end{equation}

In [14]:
def inverse_matrix(matrix):
    det = np.linalg.det(matrix) # compute and check the determinant first
    if det == 0:
        raise TypeError("Determinant equals ZERO, the matrix is invertible")
    result = np.linalg.inv(matrix)
    return result

In [17]:
A = np.array([[-2, 6],
            [8, -4]])
inverse_matrix(A)

array([[0.1 , 0.15],
       [0.2 , 0.05]])