In [1]:
import numpy as np

In [3]:
x = np. array ([[ -1 , 2],
                [3, -4]])
k = np. array ([1 , 2])
print ('result \n', x@k)

result 
 [ 3 -5]


In [4]:
def matrix_multi_vector(matrix, vector):
    result = matrix @ vector
    return result

In [5]:
m = np. array ([[ -1 , 1, 1], [0, -4, 9]])
v = np. array ([0 , 2, 1])
result = matrix_multi_vector (m, v)
print ( result )

[3 1]


In [6]:
def matrix_multi_matrix(matrix1, matrix2):
    len_of_vector = np.matmul(matrix1, matrix2)
    return len_of_vector

In [7]:
m1 = np. array ([[0 , 1, 2], [2, -3, 1]])
m2 = np. array ([[1 , -3] ,[6 , 1], [0, -1]])
result = matrix_multi_matrix (m1 , m2)
print ( result )

[[  6  -1]
 [-16 -10]]


In [8]:
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4))[0]
m2 = np. array ([[1 , 1, 1, 1] ,[2 , 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print ( result )

[5. 5. 5. 5.]


In [15]:
m1 = np. array ([[1 , 2], [3, 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F")[0]
print(m1)

[1 3 2 4]


In [16]:
m2 = np. array ([[1 , 1, 1, 1] ,[2 , 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [17]:
def inverse_matrix(matrix):
    det = np.linalg.det(matrix) # compute and check the determinant first
    if det == 0:
        raise TypeError("Determinant equals ZERO, the matrix is invertible")
    result = np.linalg.inv(matrix)
    return result
    
m1 = np. array ([[ -2 , 6], [8, -4]])
result = inverse_matrix (m1)
print ( result )

[[0.1  0.15]
 [0.2  0.05]]
